### PR TITLE
Remove the need to pass style to children function

### PR DESCRIPTION
**Pull request by AugustoConti**

### CODE REVIEW

**Comment by frinyvonnick** [comment]
Thank you for your work @AugustoConti 🙏 It's check it tomorrow!

**Comment by frinyvonnick** [comment]
You did exactly what was described in #2 but it caused a regression.

You can see it but typing this command at the project root:

```bash
cd example && npm install && npm start
```

The list doesn't scroll nicely anymore. I was wrong about `cloneElement` it only changes props injected in the `children` function. It doesn't apply style to the DOM element generated by `cloneElement`.

The only solution I see is:

We need to wrap children into a div and apply the style to this div instead of using cloneElement. Do you see what I mean ?

Do you want to make this change @AugustoConti ? Sorry you had to implement a wrong solution because of me.

Thanks again for your work.

**Comment by AugustoConti** [comment]
Sure, no problem. I will do it.

**Comment by frinyvonnick** [comment]
👋 @AugustoConti are you still working on this ?

**Comment by AugustoConti** [comment]
Sorry @frinyvonnick , i just did it.
What do you think?

**Comment by frinyvonnick** [comment]
Don't worry, I was just asking 😄 

Nice job @AugustoConti it works like a charm 👏

I'll publish a version as soon as possible with this change.

**Comment by frinyvonnick** [comment]
Released in [1.0.0-alpha.4](https://www.npmjs.com/package/react-simple-infinite-loading/v/1.0.0-alpha.4)

**Comment by AugustoConti** [comment]
Thanks @frinyvonnick ! 👏

**Pull request merged**
